<a href="https://colab.research.google.com/github/serdar-/metabolism/blob/master/Introduction_to_Python_Practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Python 

**Metabolism**

_Serdar Ozsezen_

_28th November 2018_



## Programming at a glance

- Computers are complicated calculators. However, just like calculators they do one simple task, which is computation. In order to perform computations, we give certain instructions to the computer. These set of instructions are called **code** or **programs**. 

- You can think of the program as DNA. It gets transcribed into mRNA (machine language) by RNA polymerase (compiler or interpreter). Then mRNA gets processed in the ribosome, which is the **CPU (central processing unit)** of the computer. The output of the program is the protein. DNA, mRNA and proteins are all kept in the cytosol, which is the **memory** of the computer. 

- We use a specific languages to give instructions to the computer. These languages are called **programming languages**. Programming languages can be either close to a language that computers can easily understand (low-level languages) or humans can understand (high-level languages). **Python** is a popular high-level programming language, widely used by scientists and engineers. 

## Jupyter notebook 

- What you are currently running in your browser is called a **Jupyter notebook**. 
- Jupyter notebook provides an environment for you to write structured text (similar to Microsoft Word)  and at the same time run your code and save your analysis results. 
- All content in Jupyter notebook are divided in containers that are called **cells**. 
- In order to render the text inside a cell or run the code, you need to press **Shift + Enter** or push the play button located at the left top corner of the cell. 

## Variable definitions and types


### Definition of variables

- Data we are going to process could be in form of text or numbers.
- Data is kept in entities that are called **variables**. 
- In order to define variables, first we give a name to the variable. This name should always start with a letter or underscore, you can also use numbers within the name. However, the first character of the name of the variable cannot start with a number. Ideally name of the variable should be descriptive of the data it represents. 
- You cannot have space inside a variable name. 
- As a convention, when variable names are made out of multiple words, the words are separated with underscore. 
- Some example variable names are `R`, `vapor_pressure`, `reaction_1`, `S_matrix`.
- To define the variable we use **equals sign**, we will see the examples of it in the following chapters.

### Strings
If the data is represented as text, then we call this variable **string**. Strings are text that are written in quotes.

In [0]:
var1 = "I am a string"
var2 = 'I AM A STRING '
var3 = """I am a
multiline 
string
"""

There are numerous ways to manipulate strings. There are some examples below:

In [0]:
var2 + var1 # Connect two different text into one

'I AM A STRING I am a string'

You have probably realized that once a text starts with # (pound), it is ignored by the interpreter. Which means that you can actually write comments inside your code by putting a pound sign in front of your comment text.

In [0]:
var1[0:4] # First four letters of the text 

'I am'

In [0]:
var1[-1] # Last letter of the text

'g'

In [0]:
var3[3] # Fourth character of the text

'm'

As you can see from the examples above, indexing of the letters start from **0** instead of 1. Thus, if you want to access to the first letter in the string you need to ask the 0th element. This is also the case for other sequence-like data that we are going to see later on. 

### Numbers

In general, we use two types of numbers to make calculations in Python. These are **floating point** (`float`) or **integer** (`int`).

In [0]:
num1 = 5
num2 = 5.
num3 = 6.789

In order to learn what type of number you have, you can use the function _type_. This function will tell you what type of variable that you have and you can use it for other variables as well.

In [0]:
type(num1)

int

In [0]:
type(num2)

float

In [0]:
new_number = num1 + num2 # Adding an int to a float
type(new_number) # will give float as a result

float

Use _int_ when indexing is necessary. Besides that try to use _float_. You do not need to define floating point numbers explicitly. If you use a point in the definition of the number, Python will understand that it is a floating point number. 

#### Basic mathematical operations with numbers

Here are some examples of how you can do mathematical operations on numbers.



In [0]:
num1 + num2 # Addition 

10.0

In [0]:
num1 - num2 # Subtraction

0.0

In [0]:
negative_num2 = -num2 # Change the sign of a number

negative_num2 # You can also asign the result of an 
              # operation to a new variable

-5.0

In [0]:
num1*num2 # Multiply

25.0

In [0]:
pi = 22./7. # Divide
pi

3.142857142857143

In [0]:
num1**num2 # Power

3125.0

### Boolean

Boolean is a binary form of variable that only takes `True` or `False` as value. It is useful for comparing numbers and other types of variables. 

In [0]:
num1 > num2

False

In [0]:
num1 == num2

True

### Data structures 

Sometimes you need to keep more than one value in one variable. Then you need to use different so called **data structures**. 

#### List

One of the first and the most useful data structures in Python is called a **list**. As the name states, it is capable of keeping a list of values. 

In [0]:
list1 = [] # Empty list
list2 = [1,2]
list3 = ["1","2"]
list4 = [[1],[1,2],[1,2,3]] # Nested list (list in a list)
list5 = [1,1,2,3,3,3,3]

Similar to getting a letter on a certain index, it is also possible to get elements of a list by indexing. Indexing starts from **0**. 

In [0]:
list2[0] # First element of list2

1

In [0]:
list2[1] # Second element of list2

2

In [0]:
list4[2][1] # Second element of the third element of list4

2

In [0]:
list1.append("Jan") # Add an element to list1
list1.append("Piet")
list1

['Jan', 'Piet']

In [0]:
len(list1) # How long is list1?

2

In [0]:
list1[0] = "Mark" # Change first element to "Mark"
list1

['Mark', 'Piet']

In [0]:
len(list4) # What is the length of list4?

3

In [0]:
list1.index("Piet") # What is the index of "Piet" element?

1

_index_ only gives the first occurence of the element that you look for in the list. 

#### Tuple 

**Tuple** is similar to **list**, however it is not possible to change or manipulate its elements once it is created. However, it is possible to process it faster in comparison to **list**. If you need to keep a number of constant values in one variable, it is a very useful data structure. Tuples are defined using parantheses. 

In [0]:
tuple1 = ("this","is","a","tuple")

In [0]:
tuple1[2] # It is possible to access to its elements similar to list

'a'

In [0]:
tuple1.index("is") # Index of an element in a tuple

1

#### Dictionary 

Dictionary is actually a key-value storage. You can relate any two variables with each other and use it like that. Think of it like a table with two columns. On the first column there are keys and on the second column there are values. It is defined using curved brackets.

In [0]:
dict1 = {} # Empty dictionary 
dict2 = {1: "A", 2: "B"} 

In [0]:
dict2[1] # Value of the key 1

'A'

In [0]:
dict2[2] # Value of the key 2

'B'

In [0]:
dict2.keys() # All keys in dict2

dict_keys([1, 2])

In [0]:
dict2.values() # All values in dict2

dict_values(['A', 'B'])

In [0]:
dict1["Matthias"] = "MSB" # Create a key called "Matthias" and make "MSB" its value
dict1["Andreas"] = "MSB"
dict1

{'Andreas': 'MSB', 'Matthias': 'MSB'}

As you can see above, one important thing to be careful with dictionary is the fact that **key-value bindings are not kept in the order that you define them**. 

## Control flow

Main advantage of computer programming is to outsource the repetitive tasks. In order to carry out repetitive tasks, we use instructions that allow us to repeat some lines of code. Thus, we **control the progression of the program** and get the necessary tasks done. 

### `for` loop

`for` loop allows us to repeat the tasks within a defined number of times. 

In [0]:
for i in range(1,6): # Range is a function that creates a list of integers (from 1 to 5 in here).
  print(i)         # i is an arbitrary name for the changing value upon iteration

1
2
3
4
5


We need to draw the line between the codes that are going to be run repetitively and the code that is going to run only one time. In order to make this distinction, we use **indentation** in Python. This is why the line under `print(i)` begins with an indentation. Let us make it clear with another example:


In [0]:
for i in range(2):
  print("Da")
for i in range(3):
  print("Bum")
print("Another one bites the dust")

Da
Da
Bum
Bum
Bum
Another one bites the dust


As we see in the example above, last line of the text writes only once because last line of the code is not indented. Therefore it is not in the scope of `for` loop to be repeated. 

Therefore, **indentation is very important in Python and often errors are caused by wrong use of indentation. **

If you want to create a list from the iterated values you can also use something called **list comprehension**. It is basically a for loop that is defined in a list.

In [0]:
tuple_list1 = [i.upper() for i in tuple1] # Capitalize letters of each element in the tuple1 and put them in a list
tuple_list2 = [i[0:2] for i in tuple1] # Take first two characters of each element in tuple1 and put them in a list

In [0]:
tuple_list1

['THIS', 'IS', 'A', 'TUPLE']

In [0]:
tuple_list2

['th', 'is', 'a', 'tu']

In [0]:
squares = [i**2 for i in range(-5,6)] # Take the squares of the numbers from -5 to 4 and keep them in a list
squares

[25, 16, 9, 4, 1, 0, 1, 4, 9, 16, 25]

### `while` loop

`while` loop allows for another type of flow of control where you do not need to explicitly set the number of times that code is going to iterate. In this case, we simply set a condition and we want the code to run until this specific condition is met. 

We have bunch of numbers that are defined in a list below. Let us try to find the first number that is below 0.02 in this list of numbers.

In [0]:
data = [0.28298486, 0.18067781, 0.32572769, 0.44280147, 0.03352458,
       0.7805121 , 0.21405784, 0.57106005, 0.95434392, 0.8609314 ,
       0.81165836, 0.54759082, 0.94250277, 0.74382209, 0.11598458,
       0.60183992, 0.60872557, 0.92324317, 0.53444154, 0.15590181,
       0.08954717, 0.01616445, 0.80363048, 0.23918459, 0.13884475,
       0.96681165, 0.35998196, 0.75188695, 0.12545866, 0.61349904,
       0.97776502, 0.55933591, 0.55126962, 0.4543795 , 0.93963609,
       0.71758681, 0.06876675, 0.42008658, 0.06885745, 0.34587605,
       0.56798061, 0.08677846, 0.94064413, 0.05473897, 0.70897329,
       0.94007164, 0.92433487, 0.78702259, 0.96236832, 0.64708012,
       0.01391835, 0.40234809, 0.59158976, 0.42890466, 0.41896186,
       0.20245804, 0.29939961, 0.31413492, 0.74932118, 0.06079632,
       0.28893148, 0.1784896 , 0.36105014, 0.76111468, 0.01471541,
       0.74230656, 0.67245809, 0.32550164, 0.22351367, 0.73866749,
       0.30408488, 0.5070438 , 0.3138756 , 0.60946762, 0.11696703,
       0.41638526, 0.55288289, 0.98533532, 0.65007071, 0.33734402,
       0.17006566, 0.50629363, 0.52695524, 0.02454514, 0.81009722,
       0.83896229, 0.56991108, 0.56631264, 0.81096758, 0.10758824,
       0.33414208, 0.43419095, 0.04696024, 0.8924531 , 0.88096382,
       0.07888744, 0.84144423, 0.20973636, 0.13975401, 0.20966378]

n = 0

while data[n] > 0.02:
  n += 1 
  # 'n += 1' means add 1 to value of n
  
print("We found a value that is below 0.02!")
print("It is", data[n])
print("We iterated", n, "times to find it.")


We found a value that is below 0.02!
It is 0.01616445
We iterated 21 times to find it.


### Conditional statements (`if, elif, else`)

We use logical conditions in other to change the flow of the program and make decisions. 

It is possible to build conditional statements using *if*, *not*, *and*, *or* keywords and boolean values. 

In [0]:
for word in tuple1:
    if word.startswith("t"): # Print the string if it starts with letter "t"
        print(word)

this
tuple


In [0]:
for word in tuple1:
    if word.startswith("t") and word.endswith("s"):
        print(word)

this


In [0]:
for word in tuple1:
    if not word.startswith("t"):
        print(word)

is
a


## Functions

Functions are entities that we use in order to carry out a structured, routine task. For example, there is a certain task that you want to be carried out. It requires a long piece of code. Instead of copying and pasting your code over and over again, you can define a function and use this function.

In order to create a function, we use the keyword **`def`**. For example, following function takes the square root of a number:

In [0]:
def square_root(x):
  
  return x**(0.5)

# Take the square root of 4

square_root(4)

2.0

Here `x` is the **input argument** of the function. A function can take multiple arguments, it also be without any arguments. 

We define the scope of the function by indentation. Everything that is indented after function definition is included in the function.

Another example, this function takes a list of numbers and checks the list against another number. If the number in the list is less than the other number, the function filters it out of the list. 

In [0]:
def collect_bigger_than(check_number,number_list):
  
  for number in number_list[:]: # number_list[:] creates a copy of the actual 
    if number < check_number:   # list that we give as input. For convenience,  
      number_list.remove(number)# we do not want to modify the input list. 
  return number_list

test_list = [1,45,63,2,24,5,432,10,8]
filtered_list = collect_bigger_than(11,test_list)
filtered_list 

[45, 63, 24, 432]

## Modules 

In most cases, for example when we want to do statistical or mathematical operations, we can use the code already developed by other people. This code is kept in structures that we call **modules**. In order to use the code in the modules, we need to call them first. We call the modules with **`import`** keyword, preferably in the beginning of the code.

For our purpose, there are three commonly used modules (or libraries). These are [numpy](https://numpy.org), [scipy](https://scipy.org) and [matplotlib](https://matplotlib.org/). numpy and scipy are the libraries contain functions we can use for mathematical and statistical analysis. We use matplotlib in order to plot and make graphics from data. 


### Numpy

numpy contains the data structures that are useful for doing matrix and vector operations. In short, when we have data with a lot of numbers and we want to process this data, we can use the data structures that are available in numpy.  

#### numpy.ndarray

`ndarray` (which stands for N-dimensional array) is the data structure which we can use to keep n-dimensional data. We can have one column or one row of numbers, which is a vector. We can also have multiple columns or rows of numbers, which is a matrix. 

They are similar to list, however the difference is that you can do mathematical operations using `ndarray`s but not using lists.

In [0]:
# Import numpy module and call it "np"
# so that we do not have to write "numpy" 
# every time we use a function from there.

import numpy as np

# We can define ndarrays using a list of numbers

a = np.array([1,2,3,4,5,6,7])
b = np.array([[0.126152, 0.68474827, 0.14820641, 0.51406538, 0.3835323, 
               0.20486908, 0.27014519]])

# An example 10-by-10 matrix 

c = np.array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
              [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
              [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
              [0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
              [0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
              [0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
              [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
              [0, 1, 0, 0, 0, 0, 0, 0, 1, 0],
              [1, 0, 0, 0, 0, 0, 0, 0, 0, 1]])


Some examples for mathematical operations:

In [0]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [0]:
a + 10

array([11, 12, 13, 14, 15, 16, 17])

In [0]:
a**2

array([ 1,  4,  9, 16, 25, 36, 49])

In [0]:
a*b # Sizes of the vectors should be equal
    # to be multiplied

array([[0.126152  , 1.36949654, 0.44461923, 2.05626152, 1.9176615 ,
        1.22921448, 1.89101633]])

## Matplotlib

matplotlib library helps us to show the data on a plot. It contains multiple functions to draw different types of plots and edit them. 

# Exercies

## 1. Glucose phosphotransferase system 

<img src="http://www.life.illinois.edu/crofts/bioph354/bergman/kanal/transp/pts/ptsa.gif">

1. Using the reaction ids from the given dictionary called **`metabolites`**, generate the following reaction string: 

     **`glc__D + pep --> g6p + pyr`**

2. Key **`S`** in this dictionary corresponds to the value of the stoichiometric coefficient of the metabolite. Find the molar masses of these metabolites (you can use [Wolframalpha](https://www.wolframalpha.com) to find them) and calculate the mass difference between the two sides of the reaction. Is the mass difference close to zero?

3. Assuming 100% conversion, how many grams of pyruvate can this reaction produce from 100 mg of glucose?

In [0]:
metabolites = {'D-glucose':{'id':'glc__D','S': -1},
               'Phosphenolpyruvate': {'id':'pep','S': -1},
               'D-Glucose 6-phosphate':{'id':'g6p','S': 1},
               'Pyryvate':{'id':'pyr','S':1}}
               

In [0]:
# Your answer here

## 2. Medium left on the bench
<center><img src="https://ya-webdesign.com/images/vector-laboratory-flask-6.png" width=20%></center>
1. You need to prepare a 100 mL, 0.01 M glucose solution. Calculate how many grams of glucose you need. 
2. You prepared your medium and you left it open on your bench for 8 hours. Your lab fellows told you that water evaporates from your medium with a speed of 0.025\*T (mL/h) depending on the temperature of the lab (T is temperature in Celcius). Starting from the moment you prepared your sample, temperature profile of the lab for the next 24 hours is provided below. What is the concentration of the glucose in the medium after 8 hours? Calculate it in molar and g/L. (Tip: You can write a function that converts molar to g/L for glucose).
3. What would be the glucose concentration in molar after 24 hours?
4. After 24 hours, you realized that you cannot use the medium for your experiment because it is not 0.01 M anymore. You have another experiment where you need 0.05 M glucose medium. How many grams of glucose do you need to add in order to get 0.05 M glucose medium?
5. Write a function that takes hours as an input argument and returns the glucose concentration of the medium at the given hour in g/L.

In [0]:
# Your answer here 

import numpy as np 

# Run this if you accidentally change the temperatures
# np.random.seed(4)
# lab_temperature = np.round((20+((np.random.rand(24)-0.5))),2)

lab_temperature = np.array([20.47, 20.05, 20.47, 20.21, 20.2 , 19.72, 20.48, 
                            19.51, 19.75, 19.93, 20.28, 19.7 , 20.36, 20.48, 
                            19.66, 20.1 , 19.51, 19.89, 19.54, 20.46, 19.94, 
                            20.45, 20.29, 20.37])